consensus:
  minimum_agreement: 2
  outlier_threshold: 3
deviation_thresholds:
  labor: 0.2
  quantity: 0.1
  timeline: 0.15
model_weights:
  claude: 0.35
  gemini: 0.3
  gpt4: 0.35
safety_margins:
  high_variance: 0.1
  low_variance: 0.05
validation:
  mode: strict
